language: python

# whitelist
branches:
  only:
    - main

services:
  - docker

before_install:
  - docker-compose build --no-cache
  - docker-compose up -d
  - docker exec -it $(docker ps --format "{{.ID}}") make -f /root/catkin_ws/src/Makefile check-health

script:
  - docker exec -it $(docker ps --format "{{.ID}}") make -f /root/catkin_ws/src/Makefile test
