set(_CATKIN_CURRENT_PACKAGE "argos_bridge")
set(argos_bridge_VERSION "0.0.0")
set(argos_bridge_MAINTAINER "Peter Nikopoulos <peter@nikopoulos.net>")
set(argos_bridge_PACKAGE_FORMAT "1")
set(argos_bridge_BUILD_DEPENDS "message_generation" "std_msgs" "roscpp" "tf" "rosgraph_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "urdf" "dynamic_reconfigure")
set(argos_bridge_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "roscpp" "tf" "rosgraph_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "urdf" "dynamic_reconfigure")
set(argos_bridge_BUILDTOOL_DEPENDS "catkin")
set(argos_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(argos_bridge_EXEC_DEPENDS "message_runtime" "std_msgs" "roscpp" "tf" "rosgraph_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "urdf" "dynamic_reconfigure")
set(argos_bridge_RUN_DEPENDS "message_runtime" "std_msgs" "roscpp" "tf" "rosgraph_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "urdf" "dynamic_reconfigure")
set(argos_bridge_TEST_DEPENDS )
set(argos_bridge_DOC_DEPENDS )
set(argos_bridge_URL_WEBSITE "")
set(argos_bridge_URL_BUGTRACKER "")
set(argos_bridge_URL_REPOSITORY "")
set(argos_bridge_DEPRECATED "")